settings:
  appearance:
    theme: light
    logo: /meridiano.jpg
    logoUrl: /meridiano.jpg
    primary_color: "#EC0000"
plugins:
  datasources:
    "@evidence-dev/duckdb": {}
  components:
    "@evidence-dev/core-components": {}
deployment:
  basePath: /meridiano-analytics
